# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches:
    - development
    paths-ignore:
    - 'README.md'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload application
      uses: appleboy/scp-action@master
      with:       
        host: ${{ secrets.SERVER_IP_ADDRESS }}        
        username: ${{ secrets.SERVER_USERNAME }}      
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "/home/runner/work/spring-petclinic/spring-petclinic/target/spring-petclinic-2.4.2.jar"      
        target: "~/source"
        
    - name: Start Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}       
        username: ${{ secrets.SERVER_USERNAME }}     
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          sudo /etc/init.d/spring-petclinic-2.4.2 stop
          mv ~/source/spring-petclinic-2.4.2.jar ~/source/spring-petclinic-2.4.2-old.jar
          mv ~/source/spring-petclinic-2.4.2-latest.jar ~/source/spring-petclinic-2.4.2.jar
          sudo rm -rf /etc/init.d/spring-petclinic-2.4.2
          sudo ln -s -f ~/source/spring-petclinic-2.4.2.jar /etc/init.d/spring-petclinic-2.4.2
          sudo /etc/init.d/spring-petclinic-2.4.2 start
          rm ~/source/spring-petclinic-2.4.2-old.jar
